# Generated by Django 5.0.6 on 2024-07-03 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConstructionSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                ("unit_price", models.FloatField()),
                ("total_price", models.FloatField()),
                ("n_bc", models.CharField(max_length=255)),
                ("n_bl", models.CharField(max_length=255)),
                ("entry_date", models.DateTimeField(auto_now_add=True)),
                ("supplier", models.CharField(max_length=255)),
                ("notes", models.TextField()),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.constructionsite",
                    ),
                ),
            ],
        ),
    ]
