# Generated by Django 5.0.6 on 2024-07-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
